//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int Bank_ID { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Short_Name { get; set; }
        public string Bank_Type { get; set; }
        public string Account_No__Length { get; set; }
        public string Active { get; set; }
        public string Encoded_By { get; set; }
        public Nullable<System.DateTime> Date_and_Time_Encoded { get; set; }
    }
}
