//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Company
    {
        public int Bank_Code { get; set; }
        public int Bank_ID { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Short_Name { get; set; }
        public string Bank_Branch { get; set; }
        public string Bank_Account_No_ { get; set; }
        public string Bank_Currency { get; set; }
        public string Bank_Loan_Supplier_Code { get; set; }
        public string Importation_Code { get; set; }
        public string Payment_Entry_Code { get; set; }
        public string Active { get; set; }
    }
}
