//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string Company_Code { get; set; }
        public string Name { get; set; }
        public string Short_Name { get; set; }
        public string Letter_Code { get; set; }
        public string TIN { get; set; }
        public string Address { get; set; }
        public string Zip_Code { get; set; }
        public string Phone_No_ { get; set; }
        public string Type { get; set; }
        public string Branch { get; set; }
        public string Main_Company { get; set; }
        public string Withholding_Agent { get; set; }
        public string DBF_Code { get; set; }
        public string Active { get; set; }
    }
}
