//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_Main
    {
        public int Record_ID { get; set; }
        public int Dashboard_Code { get; set; }
        public string Module_Code { get; set; }
        public string Access_Code { get; set; }
        public string Description { get; set; }
        public string Main_Window_Dir { get; set; }
        public string WithPopUp { get; set; }
        public string NotifOnly { get; set; }
        public string Notification_Code { get; set; }
        public string Plant_Code { get; set; }
    }
}
