//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard_Detail
    {
        public int Record_ID { get; set; }
        public int Dashboard_Code { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Approve { get; set; }
        public string Disapprove { get; set; }
        public string Edit { get; set; }
        public string Delete { get; set; }
        public string Cancel { get; set; }
        public Nullable<int> Action_By_ID { get; set; }
        public string Action_By_Name { get; set; }
        public string Action { get; set; }
    }
}
