//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_ID
    {
        public string ID_No { get; set; }
        public string Picture { get; set; }
        public string Signature { get; set; }
        public string Encoded_By { get; set; }
        public System.DateTime Date_and_Time_Encoded { get; set; }
    }
}
