//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Record_ID { get; set; }
        public string ID_No { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Name_Suffix { get; set; }
        public string Name { get; set; }
        public string Origin { get; set; }
        public string Workplace { get; set; }
        public string Cost_Location { get; set; }
        public string Region { get; set; }
        public string Payroll_Workplace { get; set; }
        public string Original_Workplace { get; set; }
        public string Division_Code { get; set; }
        public string Department_Code { get; set; }
        public string Section_Code { get; set; }
        public string Position_Code { get; set; }
        public string Trainee { get; set; }
        public string Class { get; set; }
        public System.DateTime Date_Hired { get; set; }
        public Nullable<System.DateTime> Date_Terminated { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Last_Day_of_Employment { get; set; }
        public string Old_ID_No { get; set; }
        public string Applicant_No { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string TIN { get; set; }
        public string SSS_No { get; set; }
        public string PagIbig_No { get; set; }
        public string PhilHealth_No { get; set; }
        public string Bank_Account_No { get; set; }
        public string Bank_Code { get; set; }
        public string Bank_Account_Type { get; set; }
        public string Job_Level { get; set; }
        public string Position_Level { get; set; }
        public Nullable<System.DateTime> Date_Regularized { get; set; }
        public Nullable<System.DateTime> First_Evaluation_Date { get; set; }
        public Nullable<System.DateTime> Second_Evaluation_Date { get; set; }
        public Nullable<System.DateTime> Final_Evaluation_Date { get; set; }
        public Nullable<System.DateTime> Previous_Evaluation_Date { get; set; }
        public string Termination_Reason { get; set; }
        public string Civil_Status { get; set; }
        public string W4_Status { get; set; }
        public string Sex { get; set; }
        public string Citizenship { get; set; }
        public string On_Payroll { get; set; }
        public string Superior_Name { get; set; }
        public string Nickname { get; set; }
        public string Address_Region { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public string Address_Barangay { get; set; }
        public string Address_Number { get; set; }
        public string Address_Zip_Code { get; set; }
        public string Address { get; set; }
        public string Landline_No { get; set; }
        public string Mobile_No { get; set; }
        public string Email { get; set; }
        public string Emergency_Contact_Person { get; set; }
        public string Emergency_Contact_No { get; set; }
        public string Emergency_Contact_Address { get; set; }
        public string Educational_Attainment { get; set; }
        public Nullable<System.DateTime> Parental_ID { get; set; }
        public string Employee_Type { get; set; }
        public string Project_Name { get; set; }
        public string HR_PAT_Assigned { get; set; }
        public string Previous_Employer { get; set; }
        public string Previous_Employer_Tin { get; set; }
        public Nullable<System.DateTime> Previous_Employer_From { get; set; }
        public Nullable<System.DateTime> Previous_Employer_To { get; set; }
        public string Previous_Employer_Status { get; set; }
        public string Previous_Employer_Reason { get; set; }
        public Nullable<long> Reliever_ID { get; set; }
        public string Insert { get; set; }
        public string Update { get; set; }
        public string Encoded_By { get; set; }
        public System.DateTime Date_and_Time_Encoded { get; set; }
        public string Cleared { get; set; }
        public string Company_Email { get; set; }
    }
}
