//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field_Access_Restriction
    {
        public int Record_ID { get; set; }
        public string Module_Code { get; set; }
        public string Access_Code { get; set; }
        public string Field_Name { get; set; }
        public string Access_Type { get; set; }
        public string Active { get; set; }
    }
}
