//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_MAF_Attachment
    {
        public int Rec_ID { get; set; }
        public int History_ID { get; set; }
        public int Record_ID { get; set; }
        public string MAF_No { get; set; }
        public string Filename { get; set; }
    }
}
