//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Project
    {
        public int History_ID { get; set; }
        public int Project_ID { get; set; }
        public string Project_Name { get; set; }
        public Nullable<System.DateTime> Date_Started { get; set; }
        public Nullable<System.DateTime> Date_Finished { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Approver1 { get; set; }
        public string Approver2 { get; set; }
        public string Approver3 { get; set; }
        public string Approver4 { get; set; }
        public Nullable<decimal> Estimated_Budget { get; set; }
        public string Encoded_By { get; set; }
        public System.DateTime Date_and_Time_Encoded { get; set; }
    }
}
