//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Unit_Special_Conversion
    {
        public long Rec_ID { get; set; }
        public long History_ID { get; set; }
        public long Record_ID { get; set; }
        public int Item_Code { get; set; }
        public string Full_Description { get; set; }
        public string Unit_From { get; set; }
        public string Unit_To { get; set; }
        public decimal Qty_Per_Unit_From { get; set; }
    }
}
