//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_MAF_Detail
    {
        public int Rec_ID { get; set; }
        public int History_ID { get; set; }
        public int Record_ID { get; set; }
        public string MAF_No { get; set; }
        public int Category_ID { get; set; }
        public string Category { get; set; }
        public string Request { get; set; }
        public int Reason_ID { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public System.DateTime Status_DateTime { get; set; }
        public string Status_Remarks { get; set; }
        public string Status_Updated_By { get; set; }
    }
}
