//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Class> Employee_Classes { get; set; }
        public virtual DbSet<Employee_ID> Employee_IDs { get; set; }
        public virtual DbSet<Employee_Superior> Employee_Superiors { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Position_Level> Position_Levels { get; set; }
    }
}
