//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAF_Approver
    {
        public int Approver_ID { get; set; }
        public string ID_No { get; set; }
        public string Name { get; set; }
        public string Endorser_Only { get; set; }
        public string Email_CC { get; set; }
        public string MIS { get; set; }
        public string Active { get; set; }
    }
}
