//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAF_Main
    {
        public string MAF_No { get; set; }
        public string Requestor_ID_No { get; set; }
        public string Requestor_Name { get; set; }
        public string Requestor_Workplace { get; set; }
        public string Requestor_Div_Dep { get; set; }
        public System.DateTime DateTime_Requested { get; set; }
        public string Endorsed_By { get; set; }
        public Nullable<System.DateTime> DateTime_Endorsed { get; set; }
        public string Endorser_Remarks { get; set; }
        public string Final_Approver { get; set; }
        public Nullable<System.DateTime> DateTime_Approved { get; set; }
        public string Final_Approver_Remarks { get; set; }
        public string PreApproved { get; set; }
        public string Target_Date { get; set; }
        public string Status { get; set; }
        public System.DateTime Status_DateTime { get; set; }
        public string Status_Updated_By { get; set; }
        public string Status_Remarks { get; set; }
        public string Encoded_By { get; set; }
        public System.DateTime DateTime_Encoded { get; set; }
    }
}
