//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAF_Last_Series
    {
        public int Record_ID { get; set; }
        public string Table_Name { get; set; }
        public string Year { get; set; }
        public int Series { get; set; }
    }
}
