//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Master_FilesEntities : DbContext
    {
        public Master_FilesEntities()
            : base("name=Master_FilesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access_Code> Access_Codes { get; set; }
        public virtual DbSet<Attachment_Module> Attachment_Modules { get; set; }
        public virtual DbSet<Attachment_Type> Attachment_Types { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Bank_Company> Bank_Companies { get; set; }
        public virtual DbSet<BIR_ATC_Code> BIR_ATC_Codes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Currency_Conversion> Currency_Conversions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Dashboard_Detail> Dashboard_Details { get; set; }
        public virtual DbSet<Dashboard_Main> Dashboard_Mains { get; set; }
        public virtual DbSet<Error_Log> Error_Logs { get; set; }
        public virtual DbSet<Field_Access_Restriction> Field_Access_Restrictions { get; set; }
        public virtual DbSet<History_Access_Code> History_Access_Codes { get; set; }
        public virtual DbSet<History_Attachment_Module> History_Attachment_Modules { get; set; }
        public virtual DbSet<History_Attachment_Type> History_Attachment_Types { get; set; }
        public virtual DbSet<History_Bank> History_Banks { get; set; }
        public virtual DbSet<History_Currency> History_Currencies { get; set; }
        public virtual DbSet<History_Currency_Conversion> History_Currency_Conversions { get; set; }
        public virtual DbSet<History_Field_Access_Restriction> History_Field_Access_Restrictions { get; set; }
        public virtual DbSet<History_Module> History_Modules { get; set; }
        public virtual DbSet<History_Module_Permission> History_Module_Permissions { get; set; }
        public virtual DbSet<History_Project> History_Projects { get; set; }
        public virtual DbSet<History_Unit_Special_Conversion> History_Unit_Special_Conversions { get; set; }
        public virtual DbSet<History_User> History_Users { get; set; }
        public virtual DbSet<History_Users_Access> History_Users_Accesses { get; set; }
        public virtual DbSet<Item_Type> Item_Types { get; set; }
        public virtual DbSet<Last_Series> Last_Series { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Module_Permission> Module_Permissions { get; set; }
        public virtual DbSet<Payment_Type> Payment_Types { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Project_Category> Project_Categories { get; set; }
        public virtual DbSet<RegionCityBgy> RegionCityBgies { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Unit_Special_Conversion> Unit_Special_Conversions { get; set; }
        public virtual DbSet<Unit_Standard_Conversion> Unit_Standard_Conversions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Users_Access> Users_Accesses { get; set; }
        public virtual DbSet<Users_Access2> Users_Access2 { get; set; }
        public virtual DbSet<Users_Group> Users_Groups { get; set; }
        public virtual DbSet<VAT_Percent> VAT_Percents { get; set; }
        public virtual DbSet<VAT_Type> VAT_Types { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
    }
}
