//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MISEntities : DbContext
    {
        public MISEntities()
            : base("name=MISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<History_MAF_Attachment> History_MAF_Attachments { get; set; }
        public virtual DbSet<History_MAF_Detail> History_MAF_Details { get; set; }
        public virtual DbSet<History_MAF_Main> History_MAF_Mains { get; set; }
        public virtual DbSet<MAF_Approver> MAF_Approvers { get; set; }
        public virtual DbSet<MAF_Attachment> MAF_Attachments { get; set; }
        public virtual DbSet<MAF_Category> MAF_Categories { get; set; }
        public virtual DbSet<MAF_Detail> MAF_Details { get; set; }
        public virtual DbSet<MAF_Last_Series> MAF_Last_Series { get; set; }
        public virtual DbSet<MAF_Main> MAF_Mains { get; set; }
        public virtual DbSet<MAF_Reason> MAF_Reasons { get; set; }
    }
}
