//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module_Permission
    {
        public int Record_ID { get; set; }
        public string Module_Code { get; set; }
        public string Access_Code { get; set; }
        public string Add { get; set; }
        public string Edit { get; set; }
        public string Cancel { get; set; }
        public string Delete { get; set; }
        public string Print { get; set; }
        public string Approve { get; set; }
        public string Validate { get; set; }
        public string Consolidate { get; set; }
        public string Active { get; set; }
    }
}
