//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int Record_ID { get; set; }
        public string Module_Code { get; set; }
        public string Module_Name { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public string Module_Program { get; set; }
        public string Exclusive { get; set; }
        public string Payroll_Closure { get; set; }
        public string Help_Filename { get; set; }
        public string Active { get; set; }
    }
}
