//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public string Plant_Code { get; set; }
        public string Plant_Name { get; set; }
        public string Manufacturing { get; set; }
        public string Showroom { get; set; }
        public string Address { get; set; }
        public string Workplace { get; set; }
        public string Active { get; set; }
    }
}
