//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public string Code { get; set; }
        public string Position1 { get; set; }
        public short Job_Level { get; set; }
        public string Division_Code { get; set; }
        public string Dept_Code { get; set; }
        public string Section_Code { get; set; }
        public string Employee_Class { get; set; }
        public string Level { get; set; }
        public Nullable<decimal> NCR_Staff_Rate { get; set; }
        public Nullable<decimal> NCR_RF_Rate { get; set; }
        public Nullable<decimal> CAB_Staff_Rate { get; set; }
        public Nullable<decimal> CAB_RF_Rate { get; set; }
        public string Active { get; set; }
        public string Encoded_By { get; set; }
        public System.DateTime Date_and_Time_Encoded { get; set; }
    }
}
