//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int Record_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string Module_Code { get; set; }
        public string Header { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Active { get; set; }
    }
}
