//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Access2
    {
        public int Record_ID { get; set; }
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string ID_No { get; set; }
        public string Module_Code { get; set; }
        public string Workplace { get; set; }
        public string Payroll_Workplace { get; set; }
    }
}
