//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string ID_No { get; set; }
        public string Password { get; set; }
        public byte Group { get; set; }
        public string Admin { get; set; }
        public string Admin_Division { get; set; }
        public string Email { get; set; }
        public string Nickname { get; set; }
        public Nullable<short> Supplier_Group { get; set; }
        public string Active { get; set; }
    
        public virtual User Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
