//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISAF_Project.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAT_Percent
    {
        public int Record_ID { get; set; }
        public decimal Percent { get; set; }
        public Nullable<decimal> Divisor { get; set; }
        public System.DateTime Effectivity_Date { get; set; }
    }
}
